test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -33,39 +33,32 @@ jobs:
             echo "Public IP before VPN connection is $(curl -s checkip.amazonaws.com)"
 
       - run:
-          name: VPN Setup and Connect
-          command: |
-            # Dekodowanie konfiguracji VPN z base64
-            echo "$VPN_CLIENT_CONFIG" | base64 --decode > /tmp/config.ovpn
+    name: VPN Setup and Connect
+    command: |
+      echo "$VPN_CLIENT_CONFIG" | base64 --decode > /tmp/config.ovpn
 
+      sudo openvpn --config /tmp/config.ovpn \
+        --daemon \
+        --log /tmp/openvpn.log
 
-            # Jeśli VPN wymaga loginu i hasła
-            # if grep -q auth-user-pass /tmp/config.ovpn; then
-            # printf "${VPN_USER}\\n${VPN_PASSWORD}" > /tmp/vpn.login
-            # chmod 600 /tmp/vpn.login   # <-- tylko właściciel może czytać i pisać
-            # fi
+      sudo chmod 644 /tmp/openvpn.log
 
-            # Start VPN w tle
-            sudo openvpn --config /tmp/config.ovpn --daemon --log /tmp/openvpn.log
+      counter=1
+      until grep -q "Initialization Sequence Completed" /tmp/openvpn.log || [ "$counter" -ge 20 ]; do
+        echo "Waiting for VPN... ($counter)"
+        counter=$((counter+1))
+        sleep 2
+      done
 
-            # nadaj prawa do loga
-            sudo chmod 644 /tmp/openvpn.log 
-
-            # Czekanie na połączenie VPN
-            counter=1
-            until sudo grep -q "Initialization Sequence Completed" /tmp/openvpn.log || [ "$counter" -ge 15 ]; do
-            ((counter++))
-            echo "Waiting for VPN... ($counter)"
-            sleep 2
-            done
-
-            if ! sudo grep -q "Initialization Sequence Completed" /tmp/openvpn.log; then
-            echo "VPN Log Output:"
-            sudo cat /tmp/openvpn.log
-            exit 1
-            else
-            echo "VPN connected successfully."
-            fi
+      if ! grep -q "Initialization Sequence Completed" /tmp/openvpn.log; then
+        echo "VPN failed!"
+        cat /tmp/openvpn.log
+        exit 1
+      else
+        echo "VPN connected successfully."
+        curl -s https://checkip.amazonaws.com || true
+      fi
+      
 
 
       - run:
